{% set version = "2.0.0" %}

package:
  name: sphinxcontrib-htmlhelp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinxcontrib-htmlhelp/sphinxcontrib-htmlhelp-{{ version }}.tar.gz
  sha256: f5f8bb2d0d629f398bf47d0d69c07bc13b65f75a81ad9e2f71a63d4b7a2f6db2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  requires:
    - pip
    # This is a circular dependency b/c sphinx depends on this package now :-/
    - sphinx >=2
  commands:
    - pip check
  imports:
    - sphinxcontrib
    - sphinxcontrib.htmlhelp

about:
  home: http://sphinx-doc.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: sphinxcontrib-htmlhelp is a sphinx extension which ...

extra:
  recipe-maintainers:
    - ocefpaf
