{% set version = "2.0.4" %}

package:
  name: sphinxcontrib-htmlhelp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinxcontrib-htmlhelp/sphinxcontrib_htmlhelp-{{ version }}.tar.gz
  sha256: 6c26a118a05b76000738429b724a0568dbde5b72391a688577da08f11891092a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - flit-core >=3.7
  run:
    - python >=3.9
    - sphinx >=5

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.htmlhelp
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.sphinx-doc.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: sphinxcontrib-htmlhelp is a sphinx extension which ...
  doc_url: https://www.sphinx-doc.org/en/master/
  dev_url: https://github.com/sphinx-doc/sphinxcontrib-htmlhelp

extra:
  recipe-maintainers:
    - AA-Turner
    - conda-forge/sphinx
    - ocefpaf
